### ISSUE TITLE
javascript dist file?

### ISSUE THREAD

**Issue by BB-000** [jonkwheeler/ScrollScene#10]
Hi, I need to use this, but am in a Magento 2 project 🤢 so have to use their flavour of requireJs...

Is there a .js file available I can load in myself using this?

I have tried unsuccessfully to get it working in Magento2 using npm.

Cheers!!

**Comment by jonkwheeler** [comment]
Once you install it like `npm install scrollscene` navigate to `node_modules/scrollscene` can check out all the files. There's only a few there. You can import each file are you see fit. Let me know if that works.

Technically you should be able to 

```
const plugin = require('scrollscene');

console.log(plugin.ScrollScene);
console.log(plugin.ScrollObserver);
```

**Comment by BB-000** [comment]
Thanks, I did try that but couldn't get it to work. Tried again but no more luck. Loads of requirejs errors. Possibly because the .js files in node_modules are 'esm' or 'commonjs' flavours? 

e.g. "Uncaught Error: Module name "@babel/runtime/helpers/interopRequireDefault" has not been loaded yet for context: _. Use require([])"  and  "require.js:166 Uncaught Error: Module name "is-client" has not been loaded yet for context: _. Use require([])"


Anyway I've spent way too much time trying to get scrollmagic working in stupid magento 2 :(  I've decided to code a simple function myself 

Cheers!

**Comment by jonkwheeler** [comment]
@BB-000 are you on the latest version? That is a babel error, and I have that set as a dependency.

**Comment by jonkwheeler** [comment]
Just wanted to call out as well if you're interested in using ScrollMagic like this, just reference it on the CDN. `https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.7/ScrollMagic.min.js`

The entire purpose of _this_ package was really to combat ESM issues. I'd give it a shot with just using `script` inclusions like the good ol' days. Nothing wrong with that!

**Comment by BB-000** [comment]
Unfortunately even just using <script> tags doesn't play nice with Magento2... 

This simple code put into a static phtml template gives 'require.js:166 Uncaught Error: Mismatched anonymous define() module:' errors. 

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.1.1/gsap.min.js" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.1.1/MotionPathPlugin.min.js" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.7/ScrollMagic.min.js" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.7/plugins/animation.gsap.min.js" />
<script>
  gsap.from('.anim-els-fadeinup', { scale: 5, duration: 5 });
</script>
```

Anyway, unfortunately that's my problem 😅😭

**Comment by jonkwheeler** [comment]
After the script inclusion, can you do 
```
<script>
  var gsap = require('gsap');
  gsap.from('.anim-els-fadeinup', { scale: 5, duration: 5 });
</script>
```
?

**Comment by BB-000** [comment]
Thanks for the info!! Much appreciated :)  
Unfortunately none of that works though, hate to admit defeat but instead of pulling out any more hair fighting I'm just going to use a different scroll detection method..!  😿

**Comment by jonkwheeler** [comment]
give waypoints.js a shot
