### ISSUE TITLE
Toggle class, element : node not working

### ISSUE THREAD

**Issue by alancoppin** [jonkwheeler/ScrollScene#12]
Hi,

I just had an issue with the toggle class option, in the element when passing a normal DOM (for example : '.header') it's not working and checking into the code ScrollScene.js line 82, toggle.element.classList = undefined. as toggle.element is just a string not a DOM node.

I had to change to :
`toggle: {
element: document.querySelector('.header'),
className: 'turn-black',reverse: true,
}`

It's working fine with that.

I don't know if I did something wrong or maybe a bug...  Just to let you know.

**Comment by jonkwheeler** [comment]
That's correct. You cannot do `.header`. You should use a dom selector. 

```
const $element = document.querySelector('.header')

... toggle: { element: $element, className: 'turn-black',reverse: true, }```
