### ISSUE TITLE
typescript error

### ISSUE THREAD

**Issue by gaaabor** [jonkwheeler/ScrollScene#13]
Hi @jonkwheeler!

First of all thank you for your work the library works as perfectly. However I have some issues with typescript.

Our devstack is doing the type checking when you run the dev server, and I run into the following error when I do so:

```
ERROR in [at-loader] ./node_modules/scrollscene/dist/commonjs/index.d.ts:3:25 
    TS7016: Could not find a declaration file for module './scrollmagic-with-ssr'. '__PROJECT-PATH__/node_modules/scrollscene/dist/commonjs/scrollmagic-with-ssr.js' implicitly has an 'any' type.
```

```
ERROR in [at-loader] ./node_modules/scrollscene/dist/commonjs/index.d.ts:6:27 
    TS7016: Could not find a declaration file for module './scrollmagic-add-indicators'. '__PROJECT-PATH__/node_modules/scrollscene/dist/commonjs/scrollmagic-add-indicators.js' implicitly has an 'any' type.
```

I tried to declare them in the extend-types folder, the same way I do it with the main package:

![image](https://user-images.githubusercontent.com/31992795/74922598-bc420380-53cf-11ea-9d50-24c7e56d2a75.png)

For example the scrollscene.d.ts has only one line:
`declare module 'scrollscene'`

This works correctly, but when I do the same with the other two files I'm still getting the error.
`declare module 'scrollmagic-add-indicators'`
I also tried it this way:
`declare module 'scrollscene/dist/commonjs/scrollmagic-add-indicators'`

Do you have any suggestions what I do wrong?

Thanks

**Comment by jonkwheeler** [comment]
Hmm. Yeah those files aren't written in TS, thus on build there's no declaration file being output.

@gaaabor Let me see if converting them real quick does the trick.

**Comment by jonkwheeler** [comment]
@gaaabor I just released v0.0.14. Give that a shot. Not totally sure it's the answer though.

**Comment by gaaabor** [comment]
@jonkwheeler Awesome, thank you. I'll give it a go and let you know

**Comment by gaaabor** [comment]
@jonkwheeler It works, this was the problem. Thanks, keep up the good work :)
