### ISSUE TITLE
What is the difference between ScrollScene and ScrollMagic?

### ISSUE THREAD

**Issue by mvaneijgen** [jonkwheeler/ScrollScene#14]
I'm coming here from https://github.com/janpaepke/ScrollMagic/issues/926 and am a bit lost on what this package does. 

What I want is have trigger so that I can animate my GSAP animations on the scroll position. I've GSAP installed, which works great, I've ScrollMagic installed which works, but I get the error `Invalid property onOverwrite set to undefined Missing plugin? gsap.registerPlugin()`.

Does ScrollScene replace ScrollMagic in my use case? Or do I need to install it along sideScrollMagic to get rit of the warnings in my console?

**Comment by jonkwheeler** [comment]
Highly recommend reading through the README. It'll cover all of this.

> What is the difference between ScrollScene and ScrollMagic?

"ScrollScene is an extra layer on top of ScrollMagic as well as using IntersectionObserver to achieve similar effects."

`ScrollScene` uses `ScrollMagic`, it does not replace ScrollMagic. `ScrollObserver` however, uses an "IntersectionObserver to achieve similar effects.".

"This project sought out to overcome the issues of using Gsap3 with ScrollMagic, as well as ESM related problems. In the end it added more features, like video playback, scene init breakpoints, scene duration breakpoints, gsap speed controls, and using an IntersectionObserver when it fits your usecase better."

> Does ScrollScene replace ScrollMagic in my use case? Or do I need to install it along sideScrollMagic to get rit of the warnings in my console?

Here's how you install: https://github.com/jonkwheeler/ScrollScene#install

Sounds like you need to `yarn add scrollscene scrollmagic gsap` to add everything.

Here's an example with GSAP: https://github.com/jonkwheeler/ScrollScene#using-gsap-greensock

**Comment by samcreate** [comment]
Thanks @jonkwheeler!

**Comment by jonkwheeler** [comment]
You got it @samcreate
