### ISSUE TITLE
Ability to execute multiple things on a trigger

### ISSUE THREAD

**Issue by exophunk** [jonkwheeler/ScrollScene#16]
I tried to show a background video by adding a class to it (toggle) and play the video at the same time:

```javascript
const scrollObserver = new ScrollObserver({
    triggerElement: document.querySelector('.scroll-trigger-1'),
    toggle: {
        element: document.querySelector('.background-1'),
        className: 'background--is-visible'
    },
    video: {
        element: document.querySelector('.background-1 .video'),
    },
    callback: {
        active: () => {
            console.log('active');
        },
        notActive: () => {
            console.log('not active');
        }
    },
});
```

This didn't work and I found out that I can only use `toggle` OR `video` OR `callback` option, not at the same time. I had to create three different observers for that, which seems a bit verbose. Or at least the documentation didn't say that the different options only work exclusively.

Am I getting something wrong or would I need to create an extra ScrollObserver for every change? I'm thinking of just working with "callback" and do everything in there manually, but that seems to defeat the very nice interface of this library.

Thanks!

**Comment by jonkwheeler** [comment]
Hmm, let me take a peak 👀

Sidenote: I'd be better to cache the background selector, since you're looking for it twice.

```
const bg = document.querySelector('.background-1')
const video = bg.querySelector('.video')
```

**Comment by jonkwheeler** [comment]
Thanks for bringing this to my attention. Apparently I broke this with I added the callback functionality. It's working again now though. Install version 0.0.15.

Here is a link to an example like yours, with toggle, video, and callback all running on the same trigger. https://scrollscene.jonkwheeler.now.sh/?path=/story/scrollobserver-multiple-events--toggle-video-callback

**Comment by exophunk** [comment]
Thank you for the very quick fix. Works like a charm.

(Little thing: For me somehow the sourcecode doesn't load in your storybook examples? Its stuck at "Loading source")

**Comment by jonkwheeler** [comment]
Yeah, it's doesn't for me either. But for now hit up the story file https://github.com/jonkwheeler/ScrollScene/blob/master/src/stories/story.js#L1327
