### ISSUE TITLE
Refresh on window resize?

### ISSUE THREAD

**Issue by Liingon** [jonkwheeler/ScrollScene#2]
I have a gsap timeline initialized with an offset calculated from the position of some elements. When I resize the window the offset needs to be updated. How do I do that?

I have tried to run destroy() on scrollScene, and kill() on timeline and then reinitializing with the new offset, but something seems to be left over from the previous instance. The timeline triggers att seemingly random points, if I reload the page everything works again so it seems I'm missing something.

I initialize with this code:
```   
this.timeline = gsap.timeline({ paused: true });
this.timeline.to('#animated_hero', {
    x: 0,
    duration: 1,
    opacity: 0,
    paddingBottom: 30,
    ease: 'none',
});

this.scrollScene = new ScrollScene({
    triggerElement: this.triggerElement,
    gsap: {
        timeline: this.timeline,
    },
    offset: this.offset,
    duration: this.offset,
    breakpoints: { 0: false, 768: true },
});
```

**Comment by jonkwheeler** [comment]
Is this in React? Or?

**Comment by Liingon** [comment]
No react, just vanilla js.

I did use both `this.scrollScene.destroy()` and `this.scrollScene = null` but that didn't change anything. I think it may have had something to do with the parent of the animated element having `position: fixed` but I'm not sure.

Fixed it thanks to your advice by positioning the trigger with css and using `%`, so thanks for that!

**Comment by jonkwheeler** [comment]
@Liingon honestly the best advice I can offer is to create `scrollTrigger` elements. I have my css set up to show hide these automatically with `opacity: 0; visibility: hidden; pointer-events: none;` but then if my local environment, to unhide them.

Mine look like this 
![Screen Shot 2020-01-13 at 4 26 52 PM](https://user-images.githubusercontent.com/3136271/72273044-8ddb4680-3621-11ea-8d9e-44b9a90abad9.jpg)

I then move them around just using css transforms.
