### ISSUE TITLE
ScrollWizardry

### ISSUE THREAD

**Issue by tmjoen** [jonkwheeler/ScrollScene#21]
Hi, and thanks for a great library!

I was wondering if you had checked out [ScrollWizardry](https://github.com/homerjam/scrollwizardry)? It has some updates over ScrollMagic (passive event listeners, 100vh support, and is supposed to be a drop in replacement :) 

Sorry to spam the issue tracker if you already had seen this 😬

**Comment by jonkwheeler** [comment]
Yeah I've seen it. Doesn't solve everything I wanted to originally, but a good library I'm sure. This has 100vh, and so does ScrollMagic. This library is also responsive, meaning you can have a scene last 50px, then 50vh, then 100px, all at different viewports.

In the future I'll being separately ScrollObserver and ScrollScene. I haven't hammered home that they are 2 different things, but achieve very similar effects when done right. ScrollObserver is much more modern, and should be what people use 90% of the time.
