### ISSUE TITLE
Adding GSAP tween to Scene

### ISSUE THREAD

**Issue by kegesch** [jonkwheeler/ScrollScene#22]
How do you set a tween on the ScrollScene imperatively?
`scene.Scene.setTween(tween)` throws: `ERROR calling setTween() due to missing Plugin 'animation.gsap'. Please make sure to include plugins/animation.gsap.js`.
I need to set the Tween after the timeline was created.
(Currently trying to write some React component wrappers for ScrollScene, Timeline and Tween).

**Comment by jonkwheeler** [comment]
Check out the README - https://github.com/jonkwheeler/ScrollScene/blob/master/README.md

There is no `setTween` method. But the option exists. https://github.com/jonkwheeler/ScrollScene/blob/master/README.md#using-gsap-greensock
