### ISSUE TITLE
flickering, jumping when using setPin()

### ISSUE THREAD

**Issue by niklasgrewe** [jonkwheeler/ScrollScene#23]
I am using this following code to make a scale-based Animation with ScrollMagic and GSAP:

```js
const timeline = gsap.timeline({ paused: true });
timeline.fromTo(Container, 1, { scale: 2.5 }, { scale: 1 });

const containerResizeScene = new ScrollScene({
    triggerElement: document.querySelector('#hero'),
    triggerHook: 0,
    duration: 500,
    gsap: {
        timeline: timeline
    }
});
containerResizeScene.Scene.setPin('#subheading'); //set Pin
```
but when I scroll, the scalable element always jumps up briefly. I have already tested several css properties, but nothing worked really well, except I use `position: absolute` and I remove the `setPin() `function. 

I have read that a `native setPin()` function is planned... Could this be my solution? Can I wait for the implementation, or do I have to think of an alternative? 

Are there any helpful tips or workarounds?

**Comment by RemyyB** [comment]
Can you send a gif of it? I think I had the same problem, did you set a overflow-x or something on the body / html? What I did is remove the overflow from body and HTML and set a inner div in my HTML with overflow-x of hidden, that way I had no bugging / lagging scrolling with pins and gsap.

**Comment by jonkwheeler** [comment]
There's lots of reasons it could be jumping around. I'm not sure your entire code, but doing a `setPin` with ScrollMagic can be challenging to get setup right.

I'd give Petr's tutorials a shot to learn how to do this. [https://ihatetomatoes.net/get-scrollmagic-workshop/](https://ihatetomatoes.net/get-scrollmagic-workshop/)

My note of adding a native setPin is not for ScrollScene (which uses ScrollMagic). It was intended for ScrollObserver. There is no reason to add a setPin to ScrollScene with ScrollMagic already provides one. Note that this issue is not a ScrollScene issue.

Again, I'd give Petr's course a shot. It's great and goes over everything you need for pinning. Pinning requires very specific css to pull it off. Hope this points you in the right direction.

**Comment by niklasgrewe** [comment]
@RemyyB thanks for your answer. I have actually used `overflow-x: hidden` on the `body` element. But when i removed this css property, i doesn't fixed the flickering, jumping... Here is my GIF about that: 

![Zoom_Out_Effect](https://user-images.githubusercontent.com/61348836/77310644-f2401380-6cfe-11ea-8548-2d2e15bbdd49.gif)

@jonkwheeler thank you for the tip and sharing. I'll take a closer look. Maybe RemyyB can help me fix it. I am fully aware that it is of course not a ScrollScene error.

**Comment by jonkwheeler** [comment]
Quite jumpy. Have you tried using a different scene object? I noticed you have the scaling and setPin on the same one. Maybe try to make them separate. 

Also, if this is the only "pin" you need, you don't need setPin. Just make 2 separate 100vw 100vh divs, stack them with absolute positioning, put the text on one layer, and the computer on the other. Make a 3rd div who's soul purpose is the length of the scene you want, like 300vh (3 screens worth of scrolling), and then just animate both y-axis 300vh. This effectively mimics the pinning effect. I've done this on massive 50 screen length scrolling sites.

**Comment by RemyyB** [comment]
> @RemyyB thanks for your answer. I have actually used `overflow-x: hidden` on the `body` element. But when i removed this css property, i doesn't fixed the flickering, jumping... even though I use `position: absolute`, I get the error - Here is my GIF about that:
> 
> ![Zoom_Out_Effect](https://user-images.githubusercontent.com/61348836/77310644-f2401380-6cfe-11ea-8548-2d2e15bbdd49.gif)
> 
> Otherwise, could you take a look at my code when I provide you with my repo or a codesandbox?
> 

Sure, could you send me a example?

**Comment by niklasgrewe** [comment]
@RemyyB yes i removed the overflow before Scrollmagic or ScrollScene initalize...

@jonkwheeler thank you for your quick and detailed answer. To be honest, I didn't quite understand how you meant it. I posted my code on codesandbox. What do you mean, it's possible you could use my code to show me what you mean? I imagine you don't have much time for that sort of thing. But I really am a beginner in this field and I am very grateful for any professional help. 

codesandbox project: https://codesandbox.io/s/focused-stallman-vgt4y
codesandbox fullscreen: https://vgt4y.sse.codesandbox.io/

thank you for your time and effort. I really appreciate it and would be very grateful if we can solve this problem or optimize my code 👍

**Comment by niklasgrewe** [comment]
Update: i just did some work on the animation and made some changes @jonkwheeler like you told me. Maybe we can figure out the rest together...

You can find the component in `/src/components/index/Hero.svelte`

**Comment by jonkwheeler** [comment]
@niklasgrewe I added a "mimic pinning" example. It basically simulates a pin in the hero. https://scrollscene.jonkwheeler.now.sh/?path=/story/scrollscene-examples--mimic-pinning

You can see the code here: https://github.com/jonkwheeler/ScrollScene/blob/master/src/stories/story.js#L1464

Again though, if you want to learn how to use this more, please take Petr's course https://ihatetomatoes.net/get-scrollmagic-workshop/ as it shows you how to do all of this.

**Comment by niklasgrewe** [comment]
@jonkwheeler thank you very much for this example. You don't know how much you've helped me. Now the animation works as desired, no flickering or jumping - thanks for your effort

But I still have two small questions and I hope that you can answer them:

#### How can i remove Scroll Gap after scaled?
how can I set that I can scroll the page further down when the box is scaled to 1? Currently it looks like this: I scroll, the box will be scaled to 1, I scroll a little bit further and only then I can scroll down the page. How can I remove this little "scroll gap"?

i tried to set the `height` of the div `<div class="fullscreen-scene screen01" />` to e.g. `50vh` instead of `100vh` but then the animation is too short...

#### How can i calculate the scale number correctly?
I do not want to scale the box with static values and mediaQueries. Would you know a sample formula that can calculate how much I need to scale the box on each screen? Currently I scale with `2.2` and use `height: 100vh` on the figure tag. The problem is that, depending on the scaling value, I also have to change the height so that the screen-image is displayed centered. How could I make the whole thing more dynamic? Do you have an idea?

---

I'm not asking you questions. But I would be very grateful if you could give me some assistance in these two points. Thanks again for your generous support. 🎉
