### ISSUE TITLE
addIndicators not visible 

### ISSUE THREAD

**Issue by rupesx26** [jonkwheeler/ScrollScene#27]
first of all this package is a lifesaver while using scrollmagic with react as scrollmagic required server site config. 

but here I am trying to activate Indicators with scrollScene.Scene.addIndicators({ name: 'pin scene', colorEnd: '#ddd' }) but its not visible for same applied section 
note:- console-output = "export 'addIndicators' was not found in 'scrollscene'
kindly guide or provide any code snippet for same 

thanks

**Comment by jonkwheeler** [comment]
Can you provide more code than that in a codeblock?

I document it here: https://github.com/jonkwheeler/ScrollScene#add-indicators-using-the-addindicators-plugin-from-scrollmagic

**Comment by rupesx26** [comment]
`const workScroll = new ScrollScene({
              triggerElement: document.getElementById(item.route),
              triggerHook:1, 
              duration: 600,
              offset: 500, 
              reverse: false,
              scene : {
                reverse: false
              },
              gsap: {
                timeline: animationType
              }
            })

            workScroll.Scene.addIndicators({ name: 'pin scene', colorEnd: '#00000' })`

But now the issue is in console
23:48:11:486 (ScrollMagic.Scene) -> ERROR calling addIndicators() due to missing Plugin 'debug.addIndicators'. Please make sure to include plugins/debug.addIndicators.js

**Comment by jonkwheeler** [comment]
```
import { ScrollScene, addIndicators } from 'scrollscene'

const workScroll = new ScrollScene({
  triggerElement: document.getElementById(item.route),
  triggerHook: 1,
  duration: 600,
  offset: 500,
  reverse: false,
  scene: {
    reverse: false,
  },
  gsap: {
    timeline: animationType,
  },
});

workScroll.Scene.addIndicators({ name: "pin scene", colorEnd: "#00000" });
```

Did you import it? The above should work ^^.
