### ISSUE TITLE
`triggerElement` must be optional

### ISSUE THREAD

**Issue by WisdomSky** [jonkwheeler/ScrollScene#30]
The `triggerElement` property must be optional just like the original construct of the ScrollMagic's `Scene` class.

I'm only using `offsets` in all of my current implementations and I don't want to do extra work by creating elements for each.

Here's the error when I only try to use only offset:
![image](https://user-images.githubusercontent.com/6792172/79673156-5f659c80-820a-11ea-91e9-2ce528ea57e6.png)

And here's the ScrollMagic docs:
<img width="1103" alt="Screen Shot 2020-04-19 at 6 51 06 AM" src="https://user-images.githubusercontent.com/6792172/79673166-71473f80-820a-11ea-893c-5e40d4eae696.png">

**Comment by WisdomSky** [comment]
It would be better if you have all the parameters the same as the one on ScrollMagic in order to avoid confusion. We are under the impression that it's the same as ScrollMagic's scene, so we expect the parameters to be the same, except the new ones (e.g. controller).

**Comment by jonkwheeler** [comment]
This is super rare edge case, but I'll merge it.

**Comment by jonkwheeler** [comment]
Released v0.0.16

**Comment by WisdomSky** [comment]
@jonkwheeler 

I don't see why it would be considered a *super edge case* though. 
How?

**Comment by jonkwheeler** [comment]
IMO, it's super edge because I don't know anyone not setting a triggerElement, and if they wanted to use the `body` as the triggerElement, it would be smarter to just set that for readability across a team. It would be super confusing to me if my teammate had no triggerElement set. Again, that's just my opinion.

**Comment by WisdomSky** [comment]
Just because you don't know anyone that's not using a `triggerElement`, doesn't mean it's a super edge case. That's a very biased assumption. I particularly am one of those who don't use `triggerElement`.

I also think that you're confusing the use case here. We don't use the `body` as the trigger element either. We are taking advantage of the `offset`'s functionality where we can completely rid of creating nodes and just set a `value` which will act as the trigger point which in this case the value is the scroll offset. 

In ScrollMagic, the `triggerElement` was optional and the reason for that is to provide the user an alternative ability to set trigger which is via `offset`. In ScrollMagic's docs it's clearly stated that the `triggerElement` is optional only if you provide an `offset` value instead. So how can that be an edge case?

And edge case is when you try to do something that is not actually stated in the docs, but on this one it's clearly stated.
