### ISSUE TITLE
Toggle not working

### ISSUE THREAD

**Issue by jamespurnama1** [jonkwheeler/ScrollScene#36]
I'm having issues regarding the toggle option

```
const reveal = document.querySelectorAll(".reveal");

const imagesScene = new ScrollScene({
  triggerElement: "#trigger",
  duration: "95%",
  gsap: {
    timeline: tween
  },
  toggle: {
    element: reveal,
    className: 'visible'
  }
})
```
and console is returning [this](https://imgur.com/a/Ep6SisN)

I'm just using vanilla.js
ScrollMagic 2.0.7 and ScrollScene 0.0.18 (`import { ScrollScene } from 'scrollscene'`)
Sorry if the solution is obvious as I am a beginner but I did read the README.md thoroughly

**Comment by jonkwheeler** [comment]
As mentioned in the README you cannot supply the triggerElement a type of string. https://github.com/jonkwheeler/ScrollScene#options

Give it a DOM node.

```
const domNode = document.querySelector("#trigger");
```

Also, you cannot toggle multiple elements with the way you have it. You need to supply a single element.

```
const reveal = document.querySelectorAll(".reveal")[0];
```

**Comment by jamespurnama1** [comment]
Awesome it works now thank you!

is the `Invalid value option for offset: NaN` normal? It didn't appear in older versions of ScrollScene.

**Comment by jonkwheeler** [comment]
Unsure on that bit! I'll have to take a look.

**Comment by jonkwheeler** [comment]
Alright, pull `0.0.20` and it should be gone.
