### ISSUE TITLE
Possible anime.js support?

### ISSUE THREAD

**Issue by disjointed** [jonkwheeler/ScrollScene#37]
Hello!
Is there a possibility of adding [anime.js](https://animejs.com/) support to this plugin in some future? It has very similar approach to animation as `gsap` does, like single animation via `anime()` and timelines via `anime.timeline()`.
I'm asking because I already use `anime.js` in my current project and adding scroll animation via `gsap` on top would be overkill.
Thank you.

**Comment by jonkwheeler** [comment]
You shouldn't need to add gsap if you just want to use anime.js.

Both ScrollObserver and ScrollScene have the power to handle any callback you want it to fire.

With ScrollScene you want to use the ScrollMagic `method`. See the readme about this `https://github.com/jonkwheeler/ScrollScene`.

And with ScrollObserver you want to use the `callback` option. It'd end up looking like 

```
callback: { active: () => anime.timeline().play(), notActive: () => anime.timeline().pause() }
```

_Or something like that ^^._

**Comment by disjointed** [comment]
Well then, thank you!
