### ISSUE TITLE
Run callback function when trigger appears?

### ISSUE THREAD

**Issue by Liingon** [jonkwheeler/ScrollScene#4]
Is there a way to run a callback function when a trigger element appears?

**Comment by jonkwheeler** [comment]
You want a callback on the ScrollObserver?

**Comment by Liingon** [comment]
I want a way to call a function when a trigger element appears, doesn't really matter if it's on the ScrollScene or ScrollObserver. In this case to control video playback more than what is possible in the ScrollObserver at the moment, but I would likely find it useful in other situations as well.

**Comment by jonkwheeler** [comment]
I'll add something and update you. Looking into the other thing before heading out to dinner.

**Comment by jonkwheeler** [comment]
What were you looking to do with the video playback, BTW? Because I already have play/pause automatically.

**Comment by Liingon** [comment]
Yes, I saw that but I need more control than that. Like just playing the video once, and being able to set a duration that is less than the height of the page. I want it to trigger when the element becomes visible but only play for 50% of the window height for example (I'm overlaying an image so the video is only visible for a part of the time the trigger is in view). Hope that makes sense!

**Comment by jonkwheeler** [comment]
> and being able to set a duration that is less than the height of the page. I want it to trigger when the element becomes visible but only play for 50% of the window height for example

You would do this by creating a triggerElement and giving is a `height: 50vh`.

I'm not sure I follow beyond that.

**Comment by jonkwheeler** [comment]
I just released 0.0.7. There's a bunch more goodies, including the callbacks on the ScrollObserver, and you now can tap into the ScrollMagic events on ScrollScene. https://scrollscene.jonkwheeler.now.sh/?path=/story/scrollobserver-callback--console-log-active
