### ISSUE TITLE
Horizontal scroll mode

### ISSUE THREAD

**Issue by kvidek** [jonkwheeler/ScrollScene#5]
ScrollMagic controller has an option to work in horizontal scrolling containers that I cannot seem to find with your library. Example: http://scrollmagic.io/examples/basic/going_horizontal.html

Is there an easy way to make this work? Thank you...

**Comment by jonkwheeler** [comment]
Alright, I just added a bunch of stuff...

There's a bunch of ways to do this, so be sure to read the options in the README. I Added examples too. First, remember you can import `ScrollMagic` from the library as a last resort, and you'll still be protected from server-side rendering issues, at the very least. However, with this second part, I doubt you'll ever need to do that.

Second, I've added/modified a couple of options in `release v0.0.10`.

- `controller: {}`, add options to the controller, **like your `{ vertical: false }`**
- `scene: {}`, add options to the scene, previously this was called `scrollMagic`.
- `useGlobalController: true`, **which you might want to set as `false`** so you do not modify the built-in global controller used 99% of the time and is set to { vertical: true } by default. 
- `scrollScene.Scene.methods()` just in case you need to apply methods to the `ScrollMagic.Scene`.
- `scrollScene.Controller.methods()` just in case you need to apply methods to the `ScrollMagic.Controller`.

**Comment by jonkwheeler** [comment]
Just a sidenote, I'd look into using `ScrollObserver` for some events to init while side scrolling. Reason being is the Observer only cares about whether something is visible on the page, and not scroll direction. It won't do pinning, but you can still do other things. I wonder if I should dump some time into creating a way to do pinning with the Observer function 🤔

**Comment by kvidek** [comment]
@jonkwheeler great, awesome work. Will give it a try asap. Regarding the `ScrollObserver`, I gave it a try but I had some weird behaviou with gsap timeline (elements jumping around etc.) Probably there is something with my setup and implementation but couldn't make it work. Will try to set a demo so you could see what I'm talking about. 

Thanks again, keep up the awesome work. 🙌

**Comment by jonkwheeler** [comment]
@kvidek it's jumping around probably bc your animating your triggerElements, I'm guessing. What you wanna do is create a scroll trigger element that it's soul purpose is to trigger an event. That is what I do. It's a lot more predictable of an animation, and your objects won't jump around. See my comment here: https://github.com/jonkwheeler/ScrollScene/issues/2#issuecomment-573749198
