### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by adamcoulombe** [jonkwheeler/ScrollScene#6]
Getting the error `Can't resolve '@babel/runtime/helpers/esm/defineProperty' in '*********\node_modules\scrollscene\dist\esm'` . Is there some prerequisite to using this package that isnt documented?

**Comment by jonkwheeler** [comment]
Haven’t seen that one before. Got any screenshots? Or any info on which line of code doesn’t work? I do mention Polyfilling the IntersectionObserver and a few ways how.

**Comment by adamcoulombe** [comment]
Thanks for your quick response....  Attaching screenshot 
![compile error](https://i.ibb.co/QQNdX90/download.png)

**Comment by jonkwheeler** [comment]
This is odd to me. The package exports as ESM using Babel. It _also_ exports at CommonJS, which you could try, but it’ll be more bloat since CJS doesn’t tree shake. 

You should not need Babel for this to work. Babel just compiles it. Humor me. I’m starting to think this isn’t an issue with the package, but I’d love to know either way. 

Try uninstalling it and see what happens. I’m wondering if your Babel config is doing something. Also see what happens after you add scrollscene, scrollmagic, and gsap (just to make sure).

**Comment by jonkwheeler** [comment]
Also if you want, if you can replicate on something dumped down and you don’t mind sharing, I’ll dig in another day on it and see if I can help.

**Comment by jonkwheeler** [comment]
Coming back to this. I just checked the build and it does indeed spit out `@babel/runtime` in the cjs build. Can you try adding `@babel/runtime` as a dev dependency and see if it suppresses this error? I might need to change the build on this.

Also, looking for the "Field 'browser' doesn't contain a valid alias configuration" shows you might have an invalid import somewhere. See here for context: https://stackoverflow.com/a/45943348

**Comment by adamcoulombe** [comment]
Thanks for looking at this. I will get you some specifics on my config later tonight but I don't believe i am using any loaders. I am using gulp+gulp-babel and calling `webpack` from my gulpfile. I havent had an issue with other packages so far but maybe its my environment. I assumed webpack compiled the babel itself and didnt need a loader.

**Comment by jonkwheeler** [comment]
Cool man, really interested in this so keep me posted!

**Comment by jeroenmaas** [comment]
Hi,

I'm getting the same error:

```
ERROR in ./node_modules/scrollscene/dist/esm/ScrollObserver.js
Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/defineProperty' in '[redacted]\assets\node_modules\scrollscene\dist\esm'
 @ ./node_modules/scrollscene/dist/esm/ScrollObserver.js 1:0-72 5:201-216
 @ ./node_modules/scrollscene/dist/esm/index.js
 @ ./src/index.js
 @ multi ./src/index.js

ERROR in ./node_modules/scrollscene/dist/esm/ScrollScene.js
Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/defineProperty' in '[redacted]\assets\node_modules\scrollscene\dist\esm'
 @ ./node_modules/scrollscene/dist/esm/ScrollScene.js 1:0-72 5:201-216
 @ ./node_modules/scrollscene/dist/esm/index.js
 @ ./src/index.js
 @ multi ./src/index.js

ERROR in ./node_modules/scrollscene/dist/esm/helpers/isObject.js
Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/typeof' in '[redacted]\assets\node_modules\scrollscene\dist\esm\helpers'
 @ ./node_modules/scrollscene/dist/esm/helpers/isObject.js 1:0-56 3:9-16
 @ ./node_modules/scrollscene/dist/esm/helpers/index.js
 @ ./node_modules/scrollscene/dist/esm/ScrollObserver.js
 @ ./node_modules/scrollscene/dist/esm/index.js
 @ ./src/index.js
 @ multi ./src/index.js
```

Here is my webpack config, it's as basic webpack as it gets.

```
const path = require('path');

module.exports = {
    entry: {
        'index': ['./src/index.js']
    },
    output: {
        filename: '[name].js',
        path: path.resolve(__dirname, 'dist')
    },
    module: {
        rules: [{
            test: /\.scss$/,
            use: [
                "style-loader", // creates style nodes from JS strings
                "css-loader", // translates CSS into CommonJS
                {
                    loader: "sass-loader",
                } // compiles Sass to CSS, using Node Sass by default
            ]
        },
            {
                test: /\.(png|jpg|gif|svg)$/,
                use: [
                    {
                        loader: 'file-loader',
                        options: {}
                    }
                ]
            }]
    },
    cache: true
};
```

index.js

```
import {ScrollScene} from 'scrollscene'
import {gsap} from 'gsap'

// create a timeline and add a tween
const myTimeline = gsap.timeline({paused: true});

myTimeline.to(document.querySelector('.logo'), {
    x: -200,
    duration: 1,
    ease: 'power2.out',
});

let test = document.querySelector('body');
const scrollScene = new ScrollScene({
    triggerElement: test,
    gsap: {
        timeline: myTimeline,
        reverseSpeed: 4,
    },
});

```

**Comment by jonkwheeler** [comment]
Thanks for your patience on this guys, and bringing this to my attention. According to the babel docs, `@babel/runtime` is no longer included with babel 7+, and it needs to be included as a dependency, https://babeljs.io/docs/en/babel-runtime#installation. Because I already had it installed on my environments, I didn't catch this. My bad.

I've added it as a dependency and _I think_ the latest release of `0.0.12` will work. Can you give it a shot and see? Thanks!

**Comment by jonkwheeler** [comment]
Hey 👋 I think I'll close this out for now. If you have more issues, lemme know.
