### ISSUE TITLE
GSAP Tweening example

### ISSUE THREAD

**Issue by Konafets** [jonkwheeler/ScrollScene#7]
Can you add a more detailed explanation about how to install this lib together with GSAP. Which version is compatible?

Also I would like know more in depth how to create a Tween in GSAP. I tried one of the provided examples but it did not work/tween anything, although the trigger got fired. 

My current use case is, that that an animation should play as soon as is enters the viewport and this implicates also, that it should play if it already in the viewport on page load. Can you provide something like this?

**Comment by jonkwheeler** [comment]
The README has a lot of detail. I'd recommend browsing that again. https://github.com/jonkwheeler/ScrollScene

To install gsap run `yarn add gsap`. 

You can use gsap on both `ScrollScene` and `ScrollObserver`. https://github.com/jonkwheeler/ScrollScene#using-gsap-greensock, so you can take your pick.

It should work on both gsap2 and gsap3, but I see no reason to use gsap2 at this point. The only caveat to keep in mind that it's an animation, and unless you pause the animation on page load, it'll play regardless of the trigger. This is why my examples show `const tl = gsap.timeline({ paused: true })`, which is creating a timeline, and immediately pausing it.

If you're new to gsap, I'd recommend learning stuff over there. https://greensock.com/

If you need a beginner course, Petr's is great and still relevant. https://ihatetomatoes.net/get-greensock-101/ 

Here is a basic example. 

```
// create a timeline and add a tween
const tl = gsap.timeline({ paused: true })
const squareElement = document.querySelector('#square')
const myTrigger = document.querySelector('#my-trigger')

tl.to(squareElement, {
  x: -200,
  duration: 1,
  ease: 'power2.out',
})

const scrollObserver = new ScrollObserver({
  triggerElement: myTrigger,
  gsap: {
    timeline: tl,
  },
})
```

**Comment by Konafets** [comment]
Thanks for the fast answer. As you know the initialisation of ScrollMagic and GSAP is the pain point, I am missing the setup here. You mentioned it in your KeyPoints but not in the example like https://github.com/jonkwheeler/ScrollScene#using-gsap-greensock-and-setting-the-reservespeed.

I saw you merged PR in the ScrollMagic repository, but there is no release with this changes available. You mentioned to install ScrollMagic `npm i scrollmagic` but this takes the release from  january 2019.

Regarding the ScrollObserver: It uses the IntersectionObserver and this was my first approach ... get rid of ScrollMagic and just using IO as the guys from GSAP recommend. This was also working but IO seems not be compatible with iOS (I know, that according _caniuse_ it should be), so ScrollObserver is not an option for me.

**Comment by jonkwheeler** [comment]
To install everywhere run `yarn add scrollscene scrollmagic gsap`

To import make sure you 

```
import { gsap } from 'gsap'
import { ScrollObserver } from 'scrollscene'

const tl = gsap.timeline({ paused: true })

const scrollObserver = new ScrollObserver({})
```

I'd ignore anything with the code I merged into the ScrollMagic repo. You don't need that release to make this work. It will work with older ScrollMagic version.

As I mention on the README, you need to polyfill the IntersectionObserver. It'll work even on IE11 at that point.

**Comment by Konafets** [comment]
I have no problem with IE11 but with iOS. Grab yourself an IPad (mine has 13.x), go to https://alligator.io/js/intersection-observer/ and scroll to the very bottom. The sprites are flickering.

Another issue with iOS was the `unobserve()` Method, which seems to not get called. This leads to triggering the animation on the "way back" again.
