### ISSUE TITLE
Cannot find type definition file for 'react'.

### ISSUE THREAD

**Issue by AndriiTsok** [jonkwheeler/ScrollScene#8]
Hello,

Installed yarn add scrollscene scrollmagic for angular 9 project.

<img width="969" alt="image" src="https://user-images.githubusercontent.com/733224/73812797-175ae000-47ac-11ea-9a14-6ac4b8faa936.png">

**Comment by jonkwheeler** [comment]
@AndriiTsok good shout. 

I removed the React specific typings (I'm used to writing types for React) and shipped v0.0.11. Thanks.
