### ISSUE TITLE
How to add plugins like addIndicators?

### ISSUE THREAD

**Issue by RemyyB** [jonkwheeler/ScrollScene#9]
I try to add indicators using this plugin via NPM, tried importing and adding addIndicators to the controller as option in new ScollScene, but this isn't working, also tried to add to scene but not working too.

I imported the addIndicators plugin as a require, maybe that's the issue?

```
import {ScrollScene} from 'scrollscene';
import {gsap} from 'gsap';

require('scrollmagic/scrollmagic/minified/plugins/debug.addIndicators.min');

const myTimeline = gsap.timeline({paused: true})
   .from($(this).find('.element'), {
     duration: 0.8,
     delay: 0.5,
     opacity: 0,
   });

new ScrollScene({
    triggerElement: this,
    scene: {
      addIndicators: {
        name: 'sdffds',
        colorEnd: 'blue',
      },
    },
    controller: {
      addIndicators: true,
    },
    gsap: {
      timeline: myTimeline,
    },
});
```

**Comment by jonkwheeler** [comment]
So far I didn't add this. The `addIndicators` file is quite massive, and is not ESM compatible. It would only bloat your code. I'd love to add this feature in the future, but it's quite a large under taking right now.

I think the best way is to make ScrollTrigger element. See here about how I do it. https://github.com/jonkwheeler/ScrollScene/issues/2#issuecomment-573749198

But truthfully, I wouldn't bother messing with addIndicators if you can help yourself. It's not necessary 99%. Again though, the future I could work on this as I see it's value.

**Comment by jonkwheeler** [comment]
Added this to the Next Steps https://github.com/jonkwheeler/ScrollScene/blob/master/README.md#next-steps

**Comment by jonkwheeler** [comment]
I decided to just go for it on this one. 

**I added the addIndicators plugin 🎉**. See here: https://github.com/jonkwheeler/ScrollScene#add-indicators-using-the-addindicators-plugin-from-scrollmagic

It's on v 0.0.13 https://github.com/jonkwheeler/ScrollScene/releases/tag/0.0.13

**Comment by jonkwheeler** [comment]
I'm noticing them not work in production (which is good anyways), but they were working for me locally. 🤔

**Comment by RemyyB** [comment]
You are a true hero! Thank you very much :), I think a lot of people will need this plugin a lot.

Will try it out next workday :)

**Comment by jonkwheeler** [comment]
@RemyyB no sweat dude. I think in a future release I would like to make a more compatible version but this probably will hold you off for now. Let me know how it works.

**Comment by RemyyB** [comment]
@jonkwheeler thank you, the plugin seems to be working correctly, thank you very much! Cheers!

**Comment by RemyyB** [comment]
Hi there,

I saw this isn't working on the ScollObserver, does this have a specific reason?

This solution works great btw, thank you!

Remy

**Comment by jonkwheeler** [comment]
`ScrollObserver` has nothing to do with ScrollMagic, and thus nothing to do with `addIndicators`. 

`ScrollObserver` is literally observing elements on your page, so you shouldn't need indicators beyond that.

I mentioned this before, but I like to make my own triggers.

> I think the best way is to make ScrollTrigger element. See here about how I do it. https://github.com/jonkwheeler/ScrollScene/issues/2#issuecomment-573749198
